### PR TITLE
Make tutorials usable

### PR DESCRIPTION
**Pull request by dulte**
Fixes most of the tutorials.

- intro_emep still doesn't work. There are some issues with it and the new test-data minimal (eg. the section on unconventionally named data does not work because current version of test-data-minimal does not include this file).

### CODE REVIEW

**Comment by heikoklein** [comment]
@thorbjoernl What is the status here?

**Comment by thorbjoernl** [comment]
I believe this was put on hold because it is blocked by https://github.com/metno/pyaerocom/issues/1211#issuecomment-2175870953

**Comment by heikoklein** [comment]
> I believe this was put on hold because it is blocked by [metno/pyaerocom#1211 (comment)](https://github.com/metno/pyaerocom/issues/1211#issuecomment-2175870953)

I don't understand that. Can't we just add a start and stop to the tutorial for collocator? Why do we need something in the tutorials which needs long-term development. Can you run through the tutorials and say what is not working?

**Comment by thorbjoernl** [comment]
It does indeed run with start and stop specified. Some other minor issues with downloading the testdata since that has been changed recently but should be fixable.

**Comment by thorbjoernl** [comment]
I don't have access to push to this repo. Could you give me access @heikoklein ?

**Comment by heikoklein** [comment]
> I don't have access to push to this repo. Could you give me access @heikoklein ?

Sorry, you should have access now.

**Comment by thorbjoernl** [comment]
I think I resolved the merge conflicts now, but probably best if somebody else gives this a review.

**Review by heikoklein — APPROVED** [review]
The output shows that these changes have been made with 0.21.0.dev0 rather than the current 0.24.0
Since the basics of this PR - making the tutorials usable again is fulfilled, I will merge. Soon coming future PRs on the tutorials are welcome.

**Comment by heikoklein** [comment]
Errors not related to this PR (but related to making tutorials usable). Please decide if you want to create new PRs for those.

In `add_stationdata.ipynb`
```! tail -n 14 AERONET_V2_SDA_od550gt1aer2010_EastAsia.csv```
must be
```! tail -n 14 demo_datasets/AERONET_V2_SDA_od550gt1aer2010_EastAsia.csv```

In `intro_emep.ipynb`:
```from pyaerocom.testdata_access import TestDataAccess``` does not exist.

Running `run_all.py`:
```Traceback (most recent call last):
  File "/home/heikok/Programme/Python/pyaerocom-tutorials/run_all.py", line 17, in <module>
    user_server_avail = const.has_access_users_database
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/rhel8/user-apps/fou-kl/aerotools/pya-v2024.11/lib/python3.11/site-packages/pyaerocom/config.py", line 330, in has_access_users_database
    chk_dir = self._check_subdirs_cfg["users-db"]
              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute '_check_subdirs_cfg'```

**Pull request merged**
