### PR TITLE
Update tutorials

### PR DESCRIPTION
**Pull request by dulte**
The tutorials did not work when a new guy tried to run them. In the tutorials only change that needed to be implemented was TestDataAccess -> AccessTestData, but there are some changes to some plotting functions in pyaerocom. These are found in a PR in pyaerocom

### CODE REVIEW

**Comment by dulte** [comment]
The tutorials also have my results now

**Comment by dulte** [comment]
@jgliss sorry to disturb you in your new job, but I can not assign reviewers, so I think you have to do it. Might be because it is a PR from my fork(?)

**Review by avaldebe — APPROVED** [review]
ready to merge

**Comment by heikoklein** [comment]
@dulte Cant this pr be closed or merged?

**Comment by thorbjoernl** [comment]
This PR no longer resolves the issue as the `AccessTestData().download()` which the tutorial relies on no longer exists in Pyaerocom (it was moved to a fixture and is therefore part of the test code).

See https://github.com/metno/pyaerocom/issues/1168

**Comment by dulte** [comment]
Blocks this PR until https://github.com/metno/pyaerocom/issues/1168 is fixed

**Comment by lewisblake** [comment]
#1168 was fixed by #1188 so this issue can go ahead now

**Comment by dulte** [comment]
Everything should now be fixed with #12

**Pull request closed without merging**
